language: xcode61

sudo: required

language: objective-c

addons:
  apt_packages:
    - pandoc

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

before_install:
  - echo "options(repos = c(CRAN='http://cran.r-project.org'))" >> ~/.Rprofile
  - curl -OL http://raw.github.com/wush978/r-travis-mac/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
  - Rscript -e "install.packages('stringi')"
  - Rscript -e "library(stringi);stri_install_icudt()"

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_BUILD_ARGS="--no-manual"
    - R_CHECK_ARGS="--no-manual --as-cran --no-vignettes"
    - PKG_CFLAGS="-g -O3 -Wall -pedantic -I../inst/include -DLOGGER_LEVEL=LL_WARN"

